// Shopistik — shared product catalogue
// Loaded before product.js / used by the product detail page. Each entry
// mirrors a card on catalog.html (and the category pages). Detail copy is
// stored as i18n keys so Description / How to Use / Ingredients stay in
// sync with the language switcher.

window.ShopistikProducts = [
  {
    id: 'rose-gold-serum',
    name: 'Rose Gold Serum',
    category: 'skincare',
    price: 48,
    tag: 'tagBestseller',
    media: 'one',
    icon: '<path d="M12 4h8v4l2 2v18H10V10l2-2z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" /><path d="M12 14h8" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodRoseGoldSerum',
    description: 'pdpDescRoseGoldSerum',
    howToUse: 'pdpUseRoseGoldSerum',
    ingredients: 'pdpIngRoseGoldSerum',
  },
  {
    id: 'hydra-bloom-moisturizer',
    name: 'Hydra Bloom Moisturizer',
    category: 'skincare',
    price: 42,
    tag: null,
    media: 'one',
    icon: '<path d="M12 4h8v4l2 2v18H10V10l2-2z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" /><path d="M12 15h8" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodHydraBloom',
    description: 'pdpDescHydraBloom',
    howToUse: 'pdpUseHydraBloom',
    ingredients: 'pdpIngHydraBloom',
  },
  {
    id: 'dew-drop-cleansing-oil',
    name: 'Dew Drop Cleansing Oil',
    category: 'skincare',
    price: 32,
    tag: 'tagNew',
    media: 'three',
    icon: '<rect x="11" y="12" width="10" height="16" rx="2" fill="none" stroke="currentColor" stroke-width="1.6" /><path d="M14 12V6a2 2 0 012-2 2 2 0 012 2v6" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" /><path d="M13 18h6" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodDewDrop',
    description: 'pdpDescDewDrop',
    howToUse: 'pdpUseDewDrop',
    ingredients: 'pdpIngDewDrop',
  },
  {
    id: 'velvet-night-repair-cream',
    name: 'Velvet Night Repair Cream',
    category: 'skincare',
    price: 56,
    tag: null,
    media: 'four',
    icon: '<rect x="8" y="12" width="16" height="14" rx="3" fill="none" stroke="currentColor" stroke-width="1.6" /><ellipse cx="16" cy="12" rx="8" ry="2.5" fill="none" stroke="currentColor" stroke-width="1.6" /><path d="M11 18h10" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodVelvetNight',
    description: 'pdpDescVelvetNight',
    howToUse: 'pdpUseVelvetNight',
    ingredients: 'pdpIngVelvetNight',
  },
  {
    id: 'bright-eyes-cream',
    name: 'Bright Eyes Cream',
    category: 'skincare',
    price: 34,
    tag: null,
    media: 'two',
    icon: '<circle cx="16" cy="17" r="9" fill="none" stroke="currentColor" stroke-width="1.6" /><circle cx="16" cy="17" r="3.5" fill="none" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodBrightEyes',
    description: 'pdpDescBrightEyes',
    howToUse: 'pdpUseBrightEyes',
    ingredients: 'pdpIngBrightEyes',
  },
  {
    id: 'petal-soft-lip-balm',
    name: 'Petal Soft Lip Balm',
    category: 'skincare',
    price: 14,
    tag: 'tagBestseller',
    media: 'two',
    icon: '<path d="M16 26s-8-5-8-11a5 5 0 019-2.8A5 5 0 0126 15c0 6-8 11-8 11z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" />',
    shortDesc: 'prodPetalLip',
    description: 'pdpDescPetalLip',
    howToUse: 'pdpUsePetalLip',
    ingredients: 'pdpIngPetalLip',
  },
  {
    id: 'velvet-matte-lipstick',
    name: 'Velvet Matte Lipstick',
    category: 'makeup',
    price: 24,
    tag: null,
    media: 'two',
    icon: '<path d="M14 4h4l1 6-1 3v15h-4V13l-1-3z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" />',
    shortDesc: 'prodVelvetLipstick',
    description: 'pdpDescVelvetLipstick',
    howToUse: 'pdpUseVelvetLipstick',
    ingredients: 'pdpIngVelvetLipstick',
  },
  {
    id: 'silk-cushion-foundation',
    name: 'Silk Cushion Foundation',
    category: 'makeup',
    price: 36,
    tag: 'tagNew',
    media: 'three',
    icon: '<circle cx="16" cy="17" r="10" fill="none" stroke="currentColor" stroke-width="1.6" /><path d="M11 8.5c1.5-2 3.2-3 5-3s3.5 1 5 3" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />',
    shortDesc: 'prodSilkFoundation',
    description: 'pdpDescSilkFoundation',
    howToUse: 'pdpUseSilkFoundation',
    ingredients: 'pdpIngSilkFoundation',
  },
  {
    id: 'golden-hour-highlighter',
    name: 'Golden Hour Highlighter',
    category: 'makeup',
    price: 29,
    tag: null,
    media: 'four',
    icon: '<rect x="9" y="9" width="14" height="14" rx="3" fill="none" stroke="currentColor" stroke-width="1.6" /><circle cx="16" cy="16" r="3" fill="none" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodGoldenHighlighter',
    description: 'pdpDescGoldenHighlighter',
    howToUse: 'pdpUseGoldenHighlighter',
    ingredients: 'pdpIngGoldenHighlighter',
  },
  {
    id: 'featherlight-mascara',
    name: 'Featherlight Mascara',
    category: 'makeup',
    price: 22,
    tag: null,
    media: 'one',
    icon: '<path d="M13 4h6l-1 8h-4z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" /><path d="M14 12v14a2 2 0 002 2 2 2 0 002-2V12" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" /><path d="M12 18l-2-1M20 18l2-1M12 22l-2 1M20 22l2 1" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" />',
    shortDesc: 'prodFeatherMascara',
    description: 'pdpDescFeatherMascara',
    howToUse: 'pdpUseFeatherMascara',
    ingredients: 'pdpIngFeatherMascara',
  },
  {
    id: 'rose-petal-blush-duo',
    name: 'Rose Petal Blush Duo',
    category: 'makeup',
    price: 26,
    tag: 'tagBestseller',
    media: 'three',
    icon: '<rect x="5" y="10" width="22" height="14" rx="4" fill="none" stroke="currentColor" stroke-width="1.6" /><circle cx="12.5" cy="17" r="3.2" fill="none" stroke="currentColor" stroke-width="1.6" /><circle cx="19.5" cy="17" r="3.2" fill="none" stroke="currentColor" stroke-width="1.6" />',
    shortDesc: 'prodRosePetalBlush',
    description: 'pdpDescRosePetalBlush',
    howToUse: 'pdpUseRosePetalBlush',
    ingredients: 'pdpIngRosePetalBlush',
  },
  {
    id: 'sheer-veil-setting-powder',
    name: 'Sheer Veil Setting Powder',
    category: 'makeup',
    price: 31,
    tag: null,
    media: 'four',
    icon: '<circle cx="16" cy="17" r="11" fill="none" stroke="currentColor" stroke-width="1.6" /><circle cx="12" cy="14" r="1" fill="currentColor" /><circle cx="20" cy="14" r="1" fill="currentColor" /><circle cx="16" cy="20" r="1" fill="currentColor" /><circle cx="12" cy="21" r="1" fill="currentColor" /><circle cx="20" cy="21" r="1" fill="currentColor" />',
    shortDesc: 'prodSheerVeilPowder',
    description: 'pdpDescSheerVeilPowder',
    howToUse: 'pdpUseSheerVeilPowder',
    ingredients: 'pdpIngSheerVeilPowder',
  },
];
